/**
 * Initiative domain types
 * The unit of planning and execution. Everything revolves around initiatives.
 */

export type InitiativeKind = 'one-time' | 'recurring' | 'evergreen';
export type InitiativeStatus =
  | 'planned'
  | 'in_progress'
  | 'launched'
  | 'completed'
  | 'paused'
  | 'retired';

export interface RevenueScenarios {
  good: number; // conservative scenario
  better: number; // moderate scenario
  best: number; // aggressive scenario
}

export interface Initiative {
  id: string;
  companyId: string;
  annualPlanId: string;
  productId: string;
  initiativeTypeId: string;
  // Core attributes
  name: string;
  description?: string;
  kind: InitiativeKind;
  status: InitiativeStatus;
  // Date anchors
  activationDate: Date; // promo launch for dated types, launch for evergreen
  eventDate?: Date; // for one-time and recurring instances; null for evergreen
  // Planning inputs
  trafficInput?: number; // expected registrants/leads
  // Revenue projections (generated by AI or manual input)
  revenueScenarios: RevenueScenarios;
  // Budget & spending
  plannedBudget: number;
  actualSpend: number;
  spendByDate?: {
    date: Date;
    amount: number;
  }[];
  // Derived metrics
  netRevenue?: number; // good/better/best - actualSpend
  roi?: number; // (netRevenue / actualSpend) * 100
  // Display
  displayOrder: number;
  // Metadata
  createdAt: Date;
  updatedAt: Date;
}

/**
 * RecurringTemplate generates recurring initiatives
 * E.g., "2 webinars per quarter" → spawns 8 instances across the year
 */
export interface RecurringTemplate {
  id: string;
  companyId: string;
  annualPlanId: string;
  initiativeTypeId: string;
  productId: string;
  // Template configuration
  name: string;
  description?: string;
  // Schedule: e.g., "2 per quarter" means 8 instances in a year
  frequencyPerQuarter: number;
  // Lead time: promo opens N days before event
  promoOffsetDays: number;
  // Generated instances
  spawnedInstanceIds: string[];
  // Metadata
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateInitiativeDTO {
  companyId: string;
  annualPlanId: string;
  productId: string;
  initiativeTypeId: string;
  name: string;
  description?: string;
  kind: InitiativeKind;
  activationDate: Date;
  eventDate?: Date;
  trafficInput?: number;
  revenueScenarios: RevenueScenarios;
  plannedBudget: number;
  displayOrder?: number;
}

export interface UpdateInitiativeDTO {
  name?: string;
  description?: string;
  status?: InitiativeStatus;
  activationDate?: Date;
  eventDate?: Date;
  trafficInput?: number;
  revenueScenarios?: Partial<RevenueScenarios>;
  plannedBudget?: number;
  actualSpend?: number;
  displayOrder?: number;
}

export interface CreateRecurringTemplateDTO {
  companyId: string;
  annualPlanId: string;
  initiativeTypeId: string;
  productId: string;
  name: string;
  description?: string;
  frequencyPerQuarter: number;
  promoOffsetDays: number;
}

export interface UpdateRecurringTemplateDTO {
  name?: string;
  description?: string;
  frequencyPerQuarter?: number;
  promoOffsetDays?: number;
}
